config/routes.rb
Rails.application.routes.draw do
  resources :grids
  resources :ventilation_logs
  resources :fans
  resources :locations
  resources :motors
  resources :motor_details
  resources :blades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/blade.rb
class Blade < ApplicationRecord
  self.inheritance_column = :_type_disabled

  belongs_to :fan
end

app/controllers/blades_controller.rb
class BladesController < ApplicationController
  before_action :set_blade, only: [:show, :edit, :update, :destroy]

  # GET /blades
  # GET /blades.json
  def index
    @blades = Blade.all
  end

  # GET /blades/1
  # GET /blades/1.json
  def show
  end

  # GET /blades/new
  def new
    @blade = Blade.new
  end

  # GET /blades/1/edit
  def edit
  end

  # POST /blades
  # POST /blades.json
  def create
    @blade = Blade.new(blade_params)

    respond_to do |format|
      if @blade.save
        format.html { redirect_to @blade, notice: 'Blade was successfully created.' }
        format.json { render :show, status: :created, location: @blade }
      else
        format.html { render :new }
        format.json { render json: @blade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blades/1
  # PATCH/PUT /blades/1.json
  def update
    respond_to do |format|
      if @blade.update(blade_params)
        format.html { redirect_to @blade, notice: 'Blade was successfully updated.' }
        format.json { render :show, status: :ok, location: @blade }
      else
        format.html { render :edit }
        format.json { render json: @blade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blades/1
  # DELETE /blades/1.json
  def destroy
    @blade.destroy
    respond_to do |format|
      format.html { redirect_to blades_url, notice: 'Blade was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_blade
      @blade = Blade.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def blade_params
      params.require(:blade).permit(:length, :length, :width, :width, :type)
    end
end

app/helpers/blades_helper.rb
module BladesHelper
end

app/views/blades/_form.html.erb
<%= form_for(blade) do |f| %>
  <% if blade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blade.errors.count, "error") %> prohibited this blade from being saved:</h2>

      <ul>
      <% blade.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :length %>
    <%= f.text_field :length %>
  </div>

  <div class="field">
    <%= f.label :width %>
    <%= f.text_field :width %>
  </div>

  <div class="field">
    <%= f.label :type %>
    <%= f.text_field :type %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/blades/edit.html.erb
<h1>Editing Blade</h1>

<%= render 'form', blade: @blade %>

<%= link_to 'Show', @blade %> |
<%= link_to 'Back', blades_path %>

app/views/blades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Blades</h1>

<table>
  <thead>
    <tr>
      <th>Length</th>
      <th>Width</th>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @blades.each do |blade| %>
      <tr>
        <td><%= blade.length %></td>
        <td><%= blade.width %></td>
        <td><%= blade.type %></td>
        <td><%= link_to 'Show', blade %></td>
        <td><%= link_to 'Edit', edit_blade_path(blade) %></td>
        <td><%= link_to 'Destroy', blade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Blade', new_blade_path %>

app/views/blades/new.html.erb
<h1>New Blade</h1>

<%= render 'form', blade: @blade %>

<%= link_to 'Back', blades_path %>

app/views/blades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Length:</strong>
  <%= @blade.length %>
</p>

<p>
  <strong>Width:</strong>
  <%= @blade.width %>
</p>

<p>
  <strong>Type:</strong>
  <%= @blade.type %>
</p>

<%= link_to 'Edit', edit_blade_path(@blade) %> |
<%= link_to 'Back', blades_path %>