config/routes.rb
Rails.application.routes.draw do
  resources :grids
  resources :ventilation_logs
  resources :fans
  resources :locations
  resources :motors
  resources :motor_details
  resources :blades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/fan.rb
class Fan < ApplicationRecord
  has_one :blade
  has_one :motor
  has_one :location
  has_many :ventilation_logs

  delegate :state, to: :motor
  Motor.states.each { |state| delegate state.to_sym, to: :motor }

  def start
    on
  end

  def stop
    off
  end

  def method_missing name, *args, &block
    if state_predicate_method? name
      self.class.delegate state.to_sym, to: :motor
      send(name)
    end
    super name, *args, &block
  end
  
  private

  def state_predicate_methods
    Motor.states.join("\\?|") << "\\?"
  end

  def state_predicate_method? name
    /(?<running_state>#{state_predicate_methods})/ =~ name
    !!$1
  end

end

app/controllers/fans_controller.rb
class FansController < ApplicationController
  before_action :set_fan, only: [:show, :edit, :update, :destroy]

  # GET /fans
  # GET /fans.json
  def index
    @fans = Fan.all
  end

  # GET /fans/1
  # GET /fans/1.json
  def show
  end

  # GET /fans/new
  def new
    @fan = Fan.new
  end

  # GET /fans/1/edit
  def edit
  end

  # POST /fans
  # POST /fans.json
  def create
    @fan = Fan.new(fan_params)

    respond_to do |format|
      if @fan.save
        format.html { redirect_to @fan, notice: 'Fan was successfully created.' }
        format.json { render :show, status: :created, location: @fan }
      else
        format.html { render :new }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /fans/1
  # PATCH/PUT /fans/1.json
  def update
    respond_to do |format|
      if @fan.update(fan_params)
        format.html { redirect_to @fan, notice: 'Fan was successfully updated.' }
        format.json { render :show, status: :ok, location: @fan }
      else
        format.html { render :edit }
        format.json { render json: @fan.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fans/1
  # DELETE /fans/1.json
  def destroy
    @fan.destroy
    respond_to do |format|
      format.html { redirect_to fans_url, notice: 'Fan was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_fan
      @fan = Fan.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def fan_params
      params.require(:fan).permit(:blade_id, :motor_id, :location_id, :state)
    end
end

app/helpers/fans_helper.rb
module FansHelper
end

app/views/fans/_form.html.erb
<%= form_for(fan) do |f| %>
  <% if fan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(fan.errors.count, "error") %> prohibited this fan from being saved:</h2>

      <ul>
      <% fan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :blade %>
    <%= f.number_field :blade %>
  </div>

  <div class="field">
    <%= f.label :motor %>
    <%= f.number_field :motor %>
  </div>

  <div class="field">
    <%= f.label :location %>
    <%= f.number_field :location %>
  </div>

  <div class="field">
    <%= f.label :state %>
    <%= f.text_field :state %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fans/edit.html.erb
<h1>Editing Fan</h1>

<%= render 'form', fan: @fan %>

<%= link_to 'Show', @fan %> |
<%= link_to 'Back', fans_path %>

app/views/fans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Fans</h1>

<table>
  <thead>
    <tr>
      <th>Blade</th>
      <th>Motor</th>
      <th>Location</th>
      <th>State</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @fans.each do |fan| %>
      <tr>
        <td><%= fan.blade.id %></td>
        <td><%= fan.motor.id %></td>
        <td><%= fan.location.grid.name %></td>
        <td><%= fan.state %></td>
        <td><%= link_to 'Show', fan %></td>
        <td><%= link_to 'Edit', edit_fan_path(fan) %></td>
        <td><%= link_to 'Destroy', fan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Fan', new_fan_path %>

app/views/fans/new.html.erb
<h1>New Fan</h1>

<%= render 'form', fan: @fan %>

<%= link_to 'Back', fans_path %>

app/views/fans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Blade:</strong>
  <%= @fan.blade.id %>
</p>

<p>
  <strong>Motor:</strong>
  <%= @fan.motor.id %>
</p>

<p>
  <strong>Location:</strong>
  <%= @fan.location.id %>
</p>

<p>
  <strong>State:</strong>
  <%= @fan.state %>
</p>

<%= link_to 'Edit', edit_fan_path(@fan) %> |
<%= link_to 'Back', fans_path %>