config/routes.rb
Rails.application.routes.draw do
  resources :grids
  resources :ventilation_logs
  resources :fans
  resources :locations
  resources :motors
  resources :motor_details
  resources :blades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/motor.rb
class Motor < ApplicationRecord
  belongs_to :fan
  has_one :motor_detail

  STATES = %w(on off high med low)

  class << states
    def states
      STATES
    end

    def running_states
      states.select { |state| state != 'off' }
    end

    def stopped_states
      states.select { |state| state != 'on' }
    end
  end

  states.each do |state|
    define_method(state) { self.update_attributes(state: state.to_s) }
  end
  
  def method_missing name, *args, &block
    if state_predicate_method? name
      return state == name[0..-2]
    end
    super name, *args, &block
  end
  
  private

  def state_predicate_methods
    STATES.join("\\?|") << "\\?"
  end

  def state_predicate_method? name
    /(?<running_state>#{state_predicate_methods})/ =~ name
    !!$1
  end
end

app/controllers/motors_controller.rb
class MotorsController < ApplicationController
  before_action :set_motor, only: [:show, :edit, :update, :destroy]

  # GET /motors
  # GET /motors.json
  def index
    @motors = Motor.all
  end

  # GET /motors/1
  # GET /motors/1.json
  def show
  end

  # GET /motors/new
  def new
    @motor = Motor.new
  end

  # GET /motors/1/edit
  def edit
  end

  # POST /motors
  # POST /motors.json
  def create
    @motor = Motor.new(motor_params)

    respond_to do |format|
      if @motor.save
        format.html { redirect_to @motor, notice: 'Motor was successfully created.' }
        format.json { render :show, status: :created, location: @motor }
      else
        format.html { render :new }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /motors/1
  # PATCH/PUT /motors/1.json
  def update
    respond_to do |format|
      if @motor.update(motor_params)
        format.html { redirect_to @motor, notice: 'Motor was successfully updated.' }
        format.json { render :show, status: :ok, location: @motor }
      else
        format.html { render :edit }
        format.json { render json: @motor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /motors/1
  # DELETE /motors/1.json
  def destroy
    @motor.destroy
    respond_to do |format|
      format.html { redirect_to motors_url, notice: 'Motor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_motor
      @motor = Motor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def motor_params
      params.require(:motor).permit(:motor_id)
    end
end

app/helpers/motors_helper.rb
module MotorsHelper
end

app/views/motors/_form.html.erb
<%= form_for(motor) do |f| %>
  <% if motor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(motor.errors.count, "error") %> prohibited this motor from being saved:</h2>

      <ul>
      <% motor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %>
    <%= f.number_field :id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/motors/edit.html.erb
<h1>Editing Motor</h1>

<%= render 'form', motor: @motor %>

<%= link_to 'Show', @motor %> |
<%= link_to 'Back', motors_path %>

app/views/motors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Motors</h1>

<table>
  <thead>
    <tr>
      <th>Motor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @motors.each do |motor| %>
      <tr>
        <td><%= motor.id %></td>
        <td><%= link_to 'Show', motor %></td>
        <td><%= link_to 'Edit', edit_motor_path(motor) %></td>
        <td><%= link_to 'Destroy', motor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Motor', new_motor_path %>

app/views/motors/new.html.erb
<h1>New Motor</h1>

<%= render 'form', motor: @motor %>

<%= link_to 'Back', motors_path %>

app/views/motors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Motor:</strong>
  <%= @motor.id %>
</p>

<%= link_to 'Edit', edit_motor_path(@motor) %> |
<%= link_to 'Back', motors_path %>