config/routes.rb
Rails.application.routes.draw do
  resources :grids
  resources :ventilation_logs
  resources :fans
  resources :locations
  resources :motors
  resources :motor_details
  resources :blades
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ArcticCooler</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<nav class="navbar navbar-default">
    <div class="container-fluid">
	<div class="navbar-header">
	<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	    <span class="sr-only">Toggle navigation</span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	    <span class="icon-bar"></span>
	</button>
	<a class="navbar-brand" href="#">Arctic Cooler</a>
	</div>

	<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	<ul class="nav navbar-nav">
	  <li class="active">
            <%= link_to "Blades", blades_path %>
	  </li>
	  <li class="active">
            <%= link_to "Motors", motors_path %>
	  </li>
	  <li class="active">
            <%= link_to "Fans", fans_path %>
	  </li>
	  <li class="active">
            <%= link_to "Locations", locations_path %>
	  </li>
	  <li class="active">
            <%= link_to "Grids", grids_path %>
	  </li>
	  <li class="active">
            <%= link_to "Ventilation Logs", ventilation_logs_path %>
	  </li>
	    <li class="dropdown">
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Reports <span class="caret"></span></a>
	    <ul class="dropdown-menu">
		<li><a href="#">Monthly</a></li>
		<li><a href="#">Weekly</a></li>
	    </ul>
	    </li>
	</ul>
	</div>
    </div>
    </nav>

    <div id="main-container" class="container">
      <div class="row">
        <div class="col-xs-9">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>